# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   #- "rules/myrules.yml"
   - rules/linuxrules.yml
   - rules/webrules.yml
   - rules/windowsrules.yml   
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["localhost:9091"]

#  - job_name: "node_exporter"
#    static_configs:
#      - targets: ["localhost:9100"]

  - job_name: "node_exporter"
    file_sd_configs: 
      - files: 
        - file_sd.yml
        - file_sd.json 

  - job_name: "wmi_exporter"
    static_configs:
      - targets: ["localhost:9182"]

  - job_name: "prom_python_app"
    static_configs:
      - targets: ["localhost:8001"]

  - job_name: "customer_exporter"
    static_configs:
      - targets: ["localhost:8001"]
